version: '3'

# used in development to make an easy and fast starting point

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
          - "8000:8000"