# Generated by Django 3.2.5 on 2021-08-10 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('industry_type', models.CharField(max_length=250, null=True)),
                ('country', models.CharField(max_length=250)),
                ('address1', models.CharField(max_length=250, null=True)),
                ('address2', models.CharField(max_length=250, null=True)),
                ('state', models.CharField(max_length=250)),
                ('pin', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DrvingLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_id', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=50)),
                ('valid_up_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_on', models.DateTimeField()),
                ('duration_in_min', models.IntegerField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.clientmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('primary_mob_no', models.CharField(max_length=15)),
                ('secondary_mob_no', models.CharField(blank=True, max_length=15, null=True)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('passport_no', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_expery_date', models.DateField(blank=True, null=True)),
                ('job_category', models.CharField(blank=True, max_length=100, null=True)),
                ('total_experence', models.FloatField(blank=True, default=0.0, null=True)),
                ('abroad_experence', models.FloatField(blank=True, default=0.0, null=True)),
                ('document_files', models.FileField(blank=True, upload_to='')),
                ('interview_status', models.CharField(blank=True, choices=[('schedule', 'SCHEDULE'), ('not_schedule', ' NOT SCHEDULE'), ('completed', 'COMPLETED'), ('seleted', 'SELECTED')], default='not_schedule', max_length=40, null=True)),
                ('visa_approval_status', models.BooleanField(default=False)),
                ('salary_details', models.TextField(blank=True, null=True)),
                ('passport_status', models.CharField(blank=True, choices=[('collected', 'COLLECTED'), ('not_collected', ' NOT COLLECTED')], max_length=40, null=True)),
                ('departure_date', models.DateField()),
                ('driving_license', models.ManyToManyField(blank=True, null=True, to='app.DrvingLicence')),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.interview')),
            ],
        ),
    ]
