# Generated by Django 3.2.5 on 2021-08-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_candidate_clientmaster_drvinglicence_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
