# Generated by Django 3.2.5 on 2021-08-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_candidate_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='scheduled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
