# Generated by Django 3.2.5 on 2021-08-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_interview_duration_in_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drvinglicence',
            name='valid_up_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
