# Generated by Django 3.2.5 on 2021-08-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_drvinglicence_valid_up_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='document_files',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
