# Generated by Django 3.2.5 on 2021-09-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_candidate_document_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='added_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
